"use client";

import React from "react";
import {
  Zap,
  Sparkles,
  ArrowRight,
  Code2,
  Clock,
  Activity,
  CheckCircle2,
} from "lucide-react";
import StreamingOutputSimulator from "./StreamingOutputSimulator";
import Module2_12Quiz from "./Module2_12Quiz";

export default function Module2_12Content() {
  return (
    <div className="space-y-10">
      {/* Hero Banner */}
      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-gradient-to-br from-teal-500/10 via-sky-500/5 to-slate-50 dark:to-slate-950 p-6 md:p-8 relative overflow-hidden transition-colors">
        <div className="space-y-3 max-w-3xl">
          <div className="flex items-center gap-2">
            <span className="text-xs font-mono font-bold uppercase tracking-wider px-3 py-1 rounded-full bg-teal-500/20 text-teal-700 dark:text-teal-300 border border-teal-500/30">
              Module 2.12 • Core Implementation
            </span>
            <span className="text-xs font-mono text-slate-500 dark:text-slate-400">
              ~15 min hands-on
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            Implementing Streaming Output for Real-Time Responses
          </h1>
          <p className="text-sm md:text-base text-slate-600 dark:text-slate-300 leading-relaxed">
            Nobody likes staring at a spinner for 8 seconds. <strong>Streaming</strong> delivers tokens as they are generated by the model, slashing perceived latency (Time to First Token) and providing an instant ChatGPT-like typing experience.
          </p>
        </div>
      </div>

      {/* Section 1: The 3 Stream Modes in LangGraph */}
      <section className="space-y-4">
        <h2 className="text-lg md:text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
          <Zap className="w-5 h-5 text-teal-500" />
          1. The 3 Stream Modes in LangGraph
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
            <span className="text-xs font-mono font-bold text-teal-600 dark:text-teal-400 uppercase">
              1. stream_mode=&quot;messages&quot;
            </span>
            <p className="text-xs text-slate-600 dark:text-slate-400 mt-1">
              Streams raw token chunks (<code className="font-mono text-[10px]">AIMessageChunk</code>) as they are sampled. Perfect for user-facing chat UIs.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
            <span className="text-xs font-mono font-bold text-sky-600 dark:text-sky-400 uppercase">
              2. stream_mode=&quot;updates&quot;
            </span>
            <p className="text-xs text-slate-600 dark:text-slate-400 mt-1">
              Emits the dictionary returned by each node as it completes. Ideal for showing multi-agent status steps.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
            <span className="text-xs font-mono font-bold text-purple-600 dark:text-purple-400 uppercase">
              3. stream_mode=&quot;values&quot;
            </span>
            <p className="text-xs text-slate-600 dark:text-slate-400 mt-1">
              Emits the full updated state dictionary after each super-step. Ideal for telemetry and timeline scrubbers.
            </p>
          </div>
        </div>
      </section>

      {/* Section 2: Code Walkthrough */}
      <section className="space-y-4">
        <h2 className="text-lg md:text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
          <Code2 className="w-5 h-5 text-sky-500" />
          2. Streaming Code in Python
        </h2>
        <div className="p-4 rounded-xl bg-slate-900 text-slate-200 font-mono text-xs border border-slate-800 overflow-x-auto">
          <pre>{`# Stream tokens to console or FastAPI SSE endpoint
for chunk, metadata in app.stream(
    {"messages": [("user", "Explain quantum computing in 2 sentences.")]},
    stream_mode="messages"
):
    if chunk.content:
        # Prints token immediately with zero delay
        print(chunk.content, end="", flush=True)`}</pre>
        </div>
      </section>

      {/* Interactive Simulator */}
      <section className="space-y-4">
        <StreamingOutputSimulator />
      </section>

      {/* Quiz */}
      <section className="space-y-4">
        <Module2_12Quiz />
      </section>

      {/* Next Step Callout */}
      <div className="p-4 rounded-xl border border-teal-500/30 bg-teal-500/10 text-xs font-mono text-slate-700 dark:text-slate-300 flex items-center justify-between">
        <span>Up Next: Module 2.13 — Configuring Async and Sync Agent Execution</span>
        <ArrowRight className="w-4 h-4 text-teal-500" />
      </div>
    </div>
  );
}
