"use client";
import React, { useState } from "react";
import confetti from "canvas-confetti";
import { CheckCircle2, XCircle, Award, RotateCcw } from "lucide-react";

const QUESTIONS = [
  {
    id: 1,
    question: "Why does traditional Test-Driven Development (TDD) fail when applied to autonomous AI agents, requiring Evaluation-Driven Development (EDD)?",
    options: [
      "Traditional testing frameworks cannot make HTTP network requests to OpenAI or Anthropic APIs.",
      "Traditional TDD requires exact, deterministic equality (assert actual == expected), whereas agents are non-deterministic and can achieve correct results through multiple valid reasoning paths.",
      "TDD is too slow to execute in modern continuous integration (CI) pipelines.",
      "Agents don't have code to test because they are written entirely in natural language system prompts.",
    ],
    correctIndex: 1,
    explanation: "Traditional TDD relies on deterministic equality assertions. An agent might write a correct SQL query using a JOIN while the reference used a subquery, or phrase a customer answer slightly differently while remaining 100% accurate. EDD evaluates semantic correctness, tool trajectory efficiency, and task success across statistical distributions rather than binary character matching.",
  },
  {
    id: 2,
    question: "What is 'Self-Enhancement Bias' in LLM-as-a-Judge systems, and how do senior AI engineers mitigate it?",
    options: [
      "LLMs generate excessively long explanations to convince human reviewers that they are intelligent.",
      "An LLM judge tends to assign higher scores to responses generated by its own model family (e.g., GPT-4o rating GPT-4o outputs higher than Claude 3.5 outputs).",
      "LLMs refuse to give low scores because their safety alignment forbids criticizing humans.",
      "Models evaluate their own execution speed faster than external API response latencies.",
    ],
    correctIndex: 1,
    explanation: "Empirical research shows LLMs exhibit self-enhancement bias: they favor the linguistic patterns, vocabulary, and formatting common to their own training data. Mitigation includes using cross-family judges (e.g., Claude evaluating GPT-4o, or a panel of different LLM families), few-shot calibrated rubrics with ground-truth examples, and human-in-the-loop calibration.",
  },
  {
    id: 3,
    question: "Why is 'Trajectory Evaluation' (evaluating intermediate tool calls and thoughts) critical in addition to 'Outcome Evaluation' (checking the final response)?",
    options: [
      "Trajectory evaluation is only used for debugging token billing, not quality.",
      "An agent can stumble upon the correct final answer through a dangerous or expensive trajectory (e.g., deleting a database table, calling 40 unnecessary API tools, or using hallucinated reasoning).",
      "Outcome evaluation is deprecated by all modern evaluation frameworks like LangSmith and Langfuse.",
      "Trajectory evaluation eliminates the need to measure user satisfaction.",
    ],
    correctIndex: 1,
    explanation: "In agent systems, the path taken matters just as much as the destination! An agent might return the correct balance inquiry, but took 18 redundant tool calls and exposed private customer data in an intermediate prompt. Trajectory evaluation measures planning efficiency, tool selection accuracy, and safety guardrails across the entire decision chain.",
  },
];

export default function Module4_11Quiz() {
  const [selected, setSelected] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const score = QUESTIONS.filter((q) => selected[q.id] === q.correctIndex).length;

  const handleSubmit = () => {
    setSubmitted(true);
    if (score === QUESTIONS.length) {
      confetti({ particleCount: 70, spread: 75, origin: { y: 0.75 } });
    }
  };

  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/90 shadow-sm p-6 md:p-8 space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 dark:border-slate-800 pb-4">
        <div>
          <span className="text-xs font-mono font-bold uppercase tracking-wider text-teal-600 dark:text-teal-400">
            Concept Mastery Check
          </span>
          <h3 className="text-lg md:text-xl font-bold text-slate-900 dark:text-white">
            Module 4.11 • Agent Evaluation & Testing Quiz
          </h3>
        </div>
        {submitted && (
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 border text-xs font-mono font-bold">
              <Award className="w-4 h-4 text-teal-500" />
              {score} / {QUESTIONS.length}
            </div>
            <button
              onClick={() => {
                setSelected({});
                setSubmitted(false);
              }}
              className="flex items-center gap-1 px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-xs font-mono transition"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              Retry
            </button>
          </div>
        )}
      </div>

      <div className="space-y-6">
        {QUESTIONS.map((q, idx) => {
          const isCorrect = selected[q.id] === q.correctIndex;
          return (
            <div
              key={q.id}
              className="p-5 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/40 space-y-3"
            >
              <div className="flex items-start gap-2">
                <span className="font-mono text-xs font-bold px-2 py-0.5 rounded bg-teal-500/20 text-teal-600 dark:text-teal-400 shrink-0">
                  Q{idx + 1}
                </span>
                <p className="text-sm font-semibold text-slate-800 dark:text-slate-200">
                  {q.question}
                </p>
              </div>

              <div className="space-y-2">
                {q.options.map((opt, optIdx) => {
                  const sel = selected[q.id] === optIdx;
                  let style =
                    "border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 hover:border-slate-300";
                  if (sel) {
                    style =
                      "border-teal-500 bg-teal-50/50 dark:bg-teal-950/40 text-teal-900 dark:text-teal-200 font-semibold";
                  }
                  if (submitted) {
                    if (optIdx === q.correctIndex) {
                      style =
                        "border-emerald-500 bg-emerald-500/10 text-emerald-800 dark:text-emerald-300 font-semibold";
                    } else if (sel && !isCorrect) {
                      style =
                        "border-red-500 bg-red-500/10 text-red-800 dark:text-red-300";
                    }
                  }
                  return (
                    <button
                      key={optIdx}
                      disabled={submitted}
                      onClick={() =>
                        !submitted &&
                        setSelected((p) => ({ ...p, [q.id]: optIdx }))
                      }
                      className={`w-full text-left p-3 rounded-lg border text-xs transition flex items-center justify-between gap-3 ${style}`}
                    >
                      <span>{opt}</span>
                      {submitted && optIdx === q.correctIndex && (
                        <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                      )}
                      {submitted && sel && !isCorrect && (
                        <XCircle className="w-4 h-4 text-red-500 shrink-0" />
                      )}
                    </button>
                  );
                })}
              </div>

              {submitted && (
                <div
                  className={`p-3 rounded-lg text-xs leading-relaxed ${
                    isCorrect
                      ? "bg-emerald-50 dark:bg-emerald-950/30 text-emerald-800 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800"
                      : "bg-red-50 dark:bg-red-950/30 text-red-800 dark:text-red-300 border border-red-200 dark:border-red-800"
                  }`}
                >
                  <span className="font-bold">Why: </span>
                  {q.explanation}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {!submitted && (
        <button
          onClick={handleSubmit}
          disabled={Object.keys(selected).length < QUESTIONS.length}
          className="w-full py-3 rounded-xl bg-teal-600 hover:bg-teal-700 disabled:opacity-50 text-white font-semibold text-xs tracking-wider uppercase transition shadow-sm"
        >
          Submit Answers
        </button>
      )}
    </div>
  );
}
